### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by baoqchau** [beam-community/elixir-companies#649] opened 2022-12-07 03:34 UTC
Hello maintainers,

The website is down at the moment I'm writing this issue. Can someone take a look?

**Comment by dzachrich** [comment] 2023-01-06 15:06
Assuming this issue is related to the changes in Heroku dyno/database offerings, @doomspork what can we do to help bring the https://elixir-companies.com/ back online?  It has been a great resource and one we would really not like to lose.  Thanks!

**Comment by doomspork** [comment] 2023-01-06 15:41
We will be bringing it back this year but after we're able to reassess how we handle approving changes because that has become a pretty sizable headache to reduce the spam and unpleasant listings.

**Comment by Tuxified** [comment] 2023-01-09 21:51
Perhaps a captcha in which the user has to solve / fix a piece of Elixir code 😝  ? In the meantime, is it possible to have a dump of the data?

**Comment by marcinkoziej** [comment] 2023-01-14 10:38
How about using a Phoenix app - https://www.paraxial.io/ ?

**Comment by marcinkoziej** [comment] 2023-01-14 10:38
Would have to ask for a free account tho

**Comment by marcinkoziej** [comment] 2023-01-19 13:11
I asked on Elixir Forum and paraxial.io founder is positive about supporting elixir-companies with a free plan:

![Screenshot from 2023-01-19 14-10-33](https://user-images.githubusercontent.com/156725/213451346-3a1f5417-0b4c-4142-a3ff-fe94dea09768.png)

**Comment by nelsonic** [comment] 2023-01-26 18:00
2023-01-26 18:00 confirmed still offline: https://elixir-companies.com 😞 
<img width="911" alt="image" src="https://user-images.githubusercontent.com/194400/214913165-42171148-ab84-44e7-8ea4-7f00e8328b80.png">

Any reason this isn't just deployed to a ***FREE*** Fly.io instance? 🤷‍♂️

**Comment by allenwyma** [comment] 2023-02-01 03:35
I'm pretty sure fly.io would be open to hosting this.

**Comment by pkananen** [comment] 2023-02-01 19:13
Launch Scout would be happy to assist in resolving this issue. Let me know if we can help.

**Comment by hwatkins** [comment] 2023-02-08 19:53
Bummer that it's been down a couple of months with multiple people offering to help revive it.

**Comment by doomspork** [comment] 2023-02-09 01:33
Hey all. I understand it can be frustrating this site is down but I'm dealing with the unexpected passing of my father, a grand parent, and a close friend all in very short succession. 

I'm trying to make time for my family, keep my employer happy, keep myself together, and still try to address open source. When I do get around to bringing this free site back online it needs a massive overhaul. It's not bot spam I'm worried about. Did you know that Elixir is used by websites that people have polarizing opinions about, on both sides of the political spectrum? Do you know how I know that? Because I've been called terrible things on Twitter and had people email my employers for companies on this website.  Now we have to review **every single posting** to make sure to doesn't link to a site that someone might strongly object to.

Again, I'm sorry the sites not up. It is on my list of things to do.

**Closed** 2023-03-01 20:20 UTC

**Comment by doomspork** [comment] 2023-03-01 21:21
@hwatkins @pkananen @allenwyma @baoqchau @dzachrich @nelsonic @Tuxified 

https://elixir-companies.com/en is back online. I will begin backfill companies this week as I review what we had already (there's more than a few companies listed I know have moved away from Elixir, I'm pruning those).

 Feel free to get involved! We've reverted to managing companies through the repository vs the DB so it can be managed by the community more readily: https://github.com/beam-community/elixir-companies/tree/main/priv/companies
